server:
  port: 3000

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/redmine
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet
  logging:
    level:
      org.springframework.security: DEBUG


application:
  security:
    jwt:
      secret-key: naskjdhi21unds1uehsi2u1ne712he18hjds891j2dej2198dh912ji
      expiration: 86400000